### ISSUE TITLE
Playing text is obstructed

### ISSUE THREAD

**Issue by nonetrix** [matthewmx86/RetroThemesFirefox#2]
I would just hide this
![Screenshot_2022-07-11_20-31-47](https://user-images.githubusercontent.com/45698918/178388702-afab3da5-1421-4b64-972a-acba7af8f942.png)

**Comment by matthewmx86** [comment]
Thanks for the feedback. Issue should now be resolved in the latest update:
`
.tab-secondary-label {
   visibility: collapse !important;
}
`
